import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://sergarb1.github.io/ApuntesProgramacion',
  base: '/ApuntesProgramacion',
  integrations: [
    starlight({
      title: {
        es: 'Apuntes Programación Java',
        va: 'Apunts Programació Java',
      },
      description: 'Curso completo de Programación en Java para DAM/DAW. CC BY-SA 4.0 — Sergi Garcia Barea',
      customCss: [
        './src/styles/custom.css',
        '@fontsource/geist-sans',
      ],
      locales: {
        root: { label: 'Español', lang: 'es' },
        va: { label: 'Valencià', lang: 'va' },
      },
      defaultLocale: 'root',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/sergarb1/ApuntesProgramacion' },
      ],
      head: [
        { tag: 'meta', attrs: { name: 'theme-color', content: '#2d8a4e' } },
        { tag: 'link', attrs: { rel: 'icon', type: 'image/png', href: '/ApuntesProgramacion/favicon.png' } },
      ],
      sidebar: [
        {
          slug: 'index',
          label: 'Inicio',
          translations: { va: 'Inici' },
        },
        {
          label: '📚 Unidades',
          translations: { va: '📚 Unitats' },
          items: [
            {
              label: '🚀 1. Introducción a Java',
              translations: { va: '🚀 1. Introducció a Java' },
              items: [
                { slug: '01-introduccion', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '01-introduccion/01-que-es-java', label: '01 · ¿Qué es Java?', translations: { va: '01 · Què és Java?' } },
                { slug: '01-introduccion/02-instalacion-jdk', label: '02 · Instalación del JDK', translations: { va: '02 · Instal·lació del JDK' } },
                { slug: '01-introduccion/03-hola-mundo', label: '03 · Tu primer programa', translations: { va: '03 · El teu primer programa' } },
                { slug: '01-introduccion/04-depurador', label: '04 · El depurador', translations: { va: '04 · El depurador' } },
                { slug: '01-introduccion/05-comentarios', label: '05 · Comentarios y documentación', translations: { va: '05 · Comentaris i documentació' } },
                { slug: '01-introduccion/06-argumentos', label: '06 · Argumentos de línea de comandos', translations: { va: '06 · Arguments de línia de comandes' } },
                { slug: '01-introduccion/07-errores-compilador', label: '07 · El compilador y sus errores', translations: { va: '07 · El compilador i els seus errors' } },
                { slug: '01-introduccion/08-ide-flujo-trabajo', label: '08 · El IDE y tu flujo de trabajo', translations: { va: "08 · L'IDE i el teu flux de treball" } },
                { slug: '01-introduccion/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '🔤 2. Variables, Tipos y Operadores',
              translations: { va: '🔤 2. Variables, Tipus i Operadors' },
              items: [
                { slug: '02-variables-tipos-operadores', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '02-variables-tipos-operadores/01-variables-tipos-primitivos', label: '01 · Variables y tipos primitivos', translations: { va: '01 · Variables i tipus primitius' } },
                { slug: '02-variables-tipos-operadores/02-string-constantes-final', label: '02 · String, constantes y final', translations: { va: '02 · String, constants i final' } },
                { slug: '02-variables-tipos-operadores/03-operadores-aritmeticos', label: '03 · Operadores aritméticos', translations: { va: '03 · Operadors aritmètics' } },
                { slug: '02-variables-tipos-operadores/04-operadores-relacionales-logicos', label: '04 · Relacionales, lógicos y ternario', translations: { va: '04 · Relacionals, lògics i ternari' } },
                { slug: '02-variables-tipos-operadores/05-casting-conversiones', label: '05 · Casting y conversiones', translations: { va: '05 · Casting i conversions' } },
                { slug: '02-variables-tipos-operadores/06-scanner-entrada-teclado', label: '06 · Scanner: leer por teclado', translations: { va: '06 · Scanner: llegir pel teclat' } },
                { slug: '02-variables-tipos-operadores/07-consola-salida-formateada', label: '07 · Consola: salida formateada y errores de entrada', translations: { va: '07 · Consola: eixida amb format i errors d\'entrada' } },
                { slug: '02-variables-tipos-operadores/08-math-random-aleatorios', label: '08 · Math.random() y números aleatorios', translations: { va: '08 · Math.random() i nombres aleatoris' } },
                { slug: '02-variables-tipos-operadores/09-metodos-string', label: '09 · Métodos útiles de String', translations: { va: '09 · Mètodes útils de String' } },
                { slug: '02-variables-tipos-operadores/10-repaso-interactivo', label: '10 · Repaso interactivo', translations: { va: '10 · Repàs interactiu' } },
              ],
            },
            {
              label: '🔀 3. Estructuras de Control',
              translations: { va: '🔀 3. Estructures de Control i Excepcions' },
              items: [
                { slug: '03-estructuras-control-excepciones', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '03-estructuras-control-excepciones/01-if-else', label: '01 · if, else if y else', translations: { va: '01 · if, else if i else' } },
                { slug: '03-estructuras-control-excepciones/02-switch', label: '02 · switch', translations: { va: '02 · switch' } },
                { slug: '03-estructuras-control-excepciones/03-bucles-while-do-while', label: '03 · Bucles: while y do-while', translations: { va: '03 · Bucles: while i do-while' } },
                { slug: '03-estructuras-control-excepciones/04-bucle-for', label: '04 · Bucle for y bucles anidados', translations: { va: '04 · Bucle for i bucles anidats' } },
                { slug: '03-estructuras-control-excepciones/05-break-continue', label: '05 · break, continue y etiquetas', translations: { va: '05 · break, continue i etiquetes' } },
                { slug: '03-estructuras-control-excepciones/06-excepciones-basicas', label: '06 · Excepciones básicas', translations: { va: '06 · Excepcions bàsiques' } },
                { slug: '03-estructuras-control-excepciones/07-try-catch-finally', label: '07 · try, catch y finally', translations: { va: '07 · try, catch i finally' } },
                { slug: '03-estructuras-control-excepciones/08-throw-excepciones-propias', label: '08 · throw y excepciones propias', translations: { va: '08 · throw i excepcions pròpies' } },
                { slug: '03-estructuras-control-excepciones/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '🅿️ 4. Arrays',
              translations: { va: '🅿️ 4. Arrays' },
              items: [
                { slug: '04-arrays', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '04-arrays/01-arrays-basicos', label: '01 · Arrays: el aparcamiento de datos', translations: { va: '01 · Arrays: l\'aparcament de dades' } },
                { slug: '04-arrays/02-recorrer-arrays', label: '02 · Recorrer arrays: for y for-each', translations: { va: '02 · Recórrer arrays: for i for-each' } },
                { slug: '04-arrays/03-arrays-multidimensionales', label: '03 · Arrays multidimensionales', translations: { va: '03 · Arrays multidimensionals' } },
                { slug: '04-arrays/04-clase-arrays', label: '04 · La clase Arrays', translations: { va: '04 · La classe Arrays' } },
                { slug: '04-arrays/05-arrays-metodos', label: '05 · Arrays y métodos', translations: { va: '05 · Arrays i mètodes' } },
                { slug: '04-arrays/06-aplicaciones-arrays', label: '06 · Aplicaciones de los arrays', translations: { va: '06 · Aplicacions dels arrays' } },
                { slug: '04-arrays/07-be-the-code', label: '07 · Be the Code', translations: { va: '07 · Be the Code' } },
                { slug: '04-arrays/08-array-revelde', label: '08 · Array-revelde', translations: { va: '08 · Array-revelde' } },
                { slug: '04-arrays/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '🧩 5. Algorítmica I: Fundamentos',
              translations: { va: '🧩 5. Algorítmica I: Fonaments' },
              items: [
                { slug: '05-algoritmica-fundamentos', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '05-algoritmica-fundamentos/01-que-es-algoritmo', label: '01 · Qué es un algoritmo', translations: { va: '01 · Què és un algoritme' } },
                { slug: '05-algoritmica-fundamentos/02-busqueda-lineal', label: '02 · Búsqueda lineal', translations: { va: '02 · Cerca lineal' } },
                { slug: '05-algoritmica-fundamentos/03-busqueda-binaria', label: '03 · Búsqueda binaria', translations: { va: '03 · Cerca binària' } },
                { slug: '05-algoritmica-fundamentos/04-ordenacion-burbuja', label: '04 · Ordenación burbuja', translations: { va: '04 · Ordenació bombolla' } },
                { slug: '05-algoritmica-fundamentos/05-ordenacion-insercion', label: '05 · Ordenación por inserción', translations: { va: '05 · Ordenació per inserció' } },
                { slug: '05-algoritmica-fundamentos/06-complejidad-big-o', label: '06 · Complejidad algorítmica: Big O', translations: { va: '06 · Complexitat algorísmica: Big O' } },
                { slug: '05-algoritmica-fundamentos/07-elegir-algoritmo', label: '07 · Elegir el algoritmo adecuado', translations: { va: "07 · Triar l'algoritme adequat" } },
                { slug: '05-algoritmica-fundamentos/08-be-the-code', label: '08 · Be the Code: búsqueda binaria desde cero', translations: { va: '08 · Be the Code: cerca binària des de zero' } },
                { slug: '05-algoritmica-fundamentos/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '⚡ 6. Algorítmica II: Técnicas',
              translations: { va: '⚡ 6. Algorítmica II: Tècniques' },
              items: [
                { slug: '06-algoritmica-tecnicas', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '06-algoritmica-tecnicas/01-recursividad', label: '01 · Recursividad', translations: { va: '01 · Recursivitat' } },
                { slug: '06-algoritmica-tecnicas/02-recursividad-ejemplos-clasicos', label: '02 · Recursividad: ejemplos clásicos', translations: { va: '02 · Recursivitat: exemples clàssics' } },
                { slug: '06-algoritmica-tecnicas/03-divide-y-venceras', label: '03 · Divide y vencerás', translations: { va: '03 · Divide i venceràs' } },
                { slug: '06-algoritmica-tecnicas/04-quicksort', label: '04 · Quicksort', translations: { va: '04 · Quicksort' } },
                { slug: '06-algoritmica-tecnicas/05-mergesort', label: '05 · Mergesort', translations: { va: '05 · Mergesort' } },
                { slug: '06-algoritmica-tecnicas/06-comparacion-ordenacion', label: '06 · Comparación: cuándo usar cada ordenación', translations: { va: '06 · Comparació: quan usar cada ordenació' } },
                { slug: '06-algoritmica-tecnicas/07-be-the-code-quicksort', label: '07 · Be the Code: quicksort desde cero', translations: { va: '07 · Be the Code: quicksort des de zero' } },
                { slug: '06-algoritmica-tecnicas/08-otras-tecnicas-algoritmicas', label: '08 · Otras técnicas algorítmicas', translations: { va: '08 · Altres tècniques algorísmiques' } },
                { slug: '06-algoritmica-tecnicas/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '🏗️ 7. POO: Clases y Objetos',
              translations: { va: '🏗️ 7. POO: Classes i Objectes' },
              items: [
                { slug: '07-poo-clases-objetos', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '07-poo-clases-objetos/01-que-es-poo', label: '01 · Qué es la POO', translations: { va: '01 · Què és la POO' } },
                { slug: '07-poo-clases-objetos/02-clases-objetos', label: '02 · Clases y objetos: el cortapastas y las galletas', translations: { va: '02 · Classes i objectes: el tallagalletas i les galetes' } },
                { slug: '07-poo-clases-objetos/03-atributos-metodos', label: '03 · Atributos y métodos', translations: { va: '03 · Atributs i mètodes' } },
                { slug: '07-poo-clases-objetos/04-constructores', label: '04 · Constructores', translations: { va: '04 · Constructors' } },
                { slug: '07-poo-clases-objetos/05-this', label: '05 · La palabra clave this', translations: { va: '05 · La paraula clau this' } },
                { slug: '07-poo-clases-objetos/06-referencias-memoria', label: '06 · Referencias, null y memoria', translations: { va: '06 · Referències, null i memòria' } },
                { slug: '07-poo-clases-objetos/07-sobrecarga-paso-valor', label: '07 · Sobrecarga y paso por valor', translations: { va: '07 · Sobrecàrrega i pas per valor' } },
                { slug: '07-poo-clases-objetos/08-be-the-code', label: '08 · Be the Code: diseña tu clase', translations: { va: '08 · Be the Code: dissenya la teua classe' } },
                { slug: '07-poo-clases-objetos/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '🔒 8. Visibilidad y Static',
              translations: { va: '🔒 8. Visibilitat, Encapsulació i Static' },
              items: [
                { slug: '08-visibilidad-encapsulacion-static', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '08-visibilidad-encapsulacion-static/01-visibilidad', label: '01 · Visibilidad: el arte de no enseñarlo todo', translations: { va: '01 · Visibilitat: l\'art de no ensenyar-ho tot' } },
                { slug: '08-visibilidad-encapsulacion-static/02-public-private-protected', label: '02 · public, private y protected', translations: { va: '02 · public, private i protected' } },
                { slug: '08-visibilidad-encapsulacion-static/03-encapsulacion', label: '03 · Encapsulación: el pilar de la POO', translations: { va: '03 · Encapsulació: el pilar de la POO' } },
                { slug: '08-visibilidad-encapsulacion-static/04-getters-setters', label: '04 · Getters y setters', translations: { va: '04 · Getters i setters' } },
                { slug: '08-visibilidad-encapsulacion-static/05-atributos-static', label: '05 · Atributos static', translations: { va: '05 · Atributs static' } },
                { slug: '08-visibilidad-encapsulacion-static/06-metodos-static', label: '06 · Métodos static y el main', translations: { va: '06 · Mètodes static i el main' } },
                { slug: '08-visibilidad-encapsulacion-static/07-constantes-static-final', label: '07 · Constantes de clase: static final', translations: { va: '07 · Constants de classe: static final' } },
                { slug: '08-visibilidad-encapsulacion-static/08-be-the-code', label: '08 · Be the Code: encapsula tu clase', translations: { va: '08 · Be the Code: encapsula la teua classe' } },
                { slug: '08-visibilidad-encapsulacion-static/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '🧬 9. Herencia, Polimorfismo e Interfaces',
              translations: { va: '🧬 9. Herència, Polimorfisme i Interfícies' },
              items: [
                { slug: '09-herencia-polimorfismo-interfaces', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '09-herencia-polimorfismo-interfaces/01-herencia', label: '01 · Herencia: cuando tus hijos siguen tus pasos', translations: { va: '01 · Herència: quan els teus fills seguixen els teus passos' } },
                { slug: '09-herencia-polimorfismo-interfaces/02-super-override', label: '02 · super y @Override', translations: { va: '02 · super i @Override' } },
                { slug: '09-herencia-polimorfismo-interfaces/03-protected-jerarquias', label: '03 · protected y jerarquías de clases', translations: { va: '03 · protected i jerarquies de classes' } },
                { slug: '09-herencia-polimorfismo-interfaces/04-polimorfismo', label: '04 · Polimorfismo: el camaleón de la POO', translations: { va: '04 · Polimorfisme: el camaleó de la POO' } },
                { slug: '09-herencia-polimorfismo-interfaces/05-instanceof-downcasting', label: '05 · instanceof y downcasting', translations: { va: '05 · instanceof i downcasting' } },
                { slug: '09-herencia-polimorfismo-interfaces/06-clase-object', label: '06 · La clase Object: el tatarabuelo', translations: { va: '06 · La classe Object: el besavi de tot' } },
                { slug: '09-herencia-polimorfismo-interfaces/07-clases-abstractas', label: '07 · Clases abstractas', translations: { va: '07 · Classes abstractes' } },
                { slug: '09-herencia-polimorfismo-interfaces/08-interfaces', label: '08 · Interfaces: el contrato que firmas', translations: { va: '08 · Interfícies: el contracte que signes' } },
                { slug: '09-herencia-polimorfismo-interfaces/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '📚 10. Colecciones',
              translations: { va: '📚 10. Col·leccions' },
              items: [
                { slug: '10-colecciones', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '10-colecciones/01-arraylist-jcf', label: '01 · ArrayList y el JCF', translations: { va: '01 · ArrayList i el JCF' } },
                { slug: '10-colecciones/02-linkedlist', label: '02 · LinkedList: la conga line', translations: { va: '02 · LinkedList: la conga line' } },
                { slug: '10-colecciones/03-hashset', label: '03 · HashSet: el portero sin duplicados', translations: { va: '03 · HashSet: el porter sense duplicats' } },
                { slug: '10-colecciones/04-treeset-linkedhashset', label: '04 · TreeSet y LinkedHashSet', translations: { va: '04 · TreeSet i LinkedHashSet' } },
                { slug: '10-colecciones/05-iterator', label: '05 · Iterator: el camarero que toma nota', translations: { va: '05 · Iterator: el cambrer que pren nota' } },
                { slug: '10-colecciones/06-collections', label: '06 · La clase Collections', translations: { va: '06 · La classe Collections' } },
                { slug: '10-colecciones/07-elegir-coleccion', label: '07 · Elegir la colección adecuada', translations: { va: '07 · Triar la col·lecció adequada' } },
                { slug: '10-colecciones/08-be-the-code', label: '08 · Be the Code', translations: { va: '08 · Be the Code' } },
                { slug: '10-colecciones/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '🗺️ 11. Genéricos y Mapas',
              translations: { va: '🗺️ 11. Genèrics i Mapes' },
              items: [
                { slug: '11-genericos-mapas', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '11-genericos-mapas/01-que-son-genericos', label: '01 · Genéricos: el <T> que lo cambió todo', translations: { va: "01 · Genèrics: el <T> que ho va canviar tot" } },
                { slug: '11-genericos-mapas/02-clases-genericas', label: '02 · Tu propia clase genérica', translations: { va: '02 · La teua pròpia classe genèrica' } },
                { slug: '11-genericos-mapas/03-diamante-type-erasure', label: '03 · El diamante y type erasure', translations: { va: '03 · El diamant i el type erasure' } },
                { slug: '11-genericos-mapas/04-metodos-genericos', label: '04 · Métodos genéricos', translations: { va: '04 · Mètodes genèrics' } },
                { slug: '11-genericos-mapas/05-wildcards', label: '05 · Wildcards: ? extends y ? super', translations: { va: '05 · Wildcards: ? extends i ? super' } },
                { slug: '11-genericos-mapas/06-hashmap', label: '06 · HashMap: la guía telefónica', translations: { va: '06 · HashMap: la guia telefònica' } },
                { slug: '11-genericos-mapas/07-treemap-otros-mapas', label: '07 · TreeMap y otros mapas', translations: { va: '07 · TreeMap i altres mapes' } },
                { slug: '11-genericos-mapas/08-elegir-estructura-datos', label: '08 · Map vs List vs Set', translations: { va: '08 · Map vs List vs Set' } },
                { slug: '11-genericos-mapas/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '📁 12. Ficheros y Regex',
              translations: { va: '📁 12. Fitxers i Expressions Regulars' },
              items: [
                { slug: '12-ficheros-regex', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '12-ficheros-regex/01-clase-file', label: '01 · La clase File', translations: { va: '01 · La classe File' } },
                { slug: '12-ficheros-regex/02-escribir-leer-texto', label: '02 · Escribir y leer texto', translations: { va: '02 · Escriure i llegir text' } },
                { slug: '12-ficheros-regex/03-try-with-resources', label: '03 · try-with-resources', translations: { va: '03 · try-with-resources' } },
                { slug: '12-ficheros-regex/04-printwriter-scanner-file', label: '04 · PrintWriter y Scanner + File', translations: { va: '04 · PrintWriter i Scanner + File' } },
                { slug: '12-ficheros-regex/05-nio-files-paths', label: '05 · NIO: Files y Paths', translations: { va: '05 · NIO: Files i Paths' } },
                { slug: '12-ficheros-regex/06-serializacion', label: '06 · Serialización', translations: { va: '06 · Serialització' } },
                { slug: '12-ficheros-regex/07-regex-basica', label: '07 · Expresiones regulares: Pattern y Matcher', translations: { va: '07 · Expressions regulars: Pattern i Matcher' } },
                { slug: '12-ficheros-regex/08-regex-aplicaciones', label: '08 · Regex en acción', translations: { va: '08 · Regex en acció' } },
                { slug: '12-ficheros-regex/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '🗄️ 13. Conexión a BD con JDBC',
              translations: { va: '🗄️ 13. Connexió a BD amb JDBC' },
              items: [
                { slug: '13-conexion-bases-datos', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '13-conexion-bases-datos/01-que-es-jdbc', label: '01 · Qué es JDBC', translations: { va: '01 · Què és JDBC' } },
                { slug: '13-conexion-bases-datos/02-conexion', label: '02 · Conexión a SQLite', translations: { va: '02 · Connexió a SQLite' } },
                { slug: '13-conexion-bases-datos/03-statement-resultset', label: '03 · Statement y ResultSet', translations: { va: '03 · Statement i ResultSet' } },
                { slug: '13-conexion-bases-datos/04-crud', label: '04 · CRUD completo', translations: { va: '04 · CRUD complet' } },
                { slug: '13-conexion-bases-datos/05-preparedstatement', label: '05 · PreparedStatement y SQL injection', translations: { va: '05 · PreparedStatement i SQL injection' } },
                { slug: '13-conexion-bases-datos/06-pattern-dao', label: '06 · El patrón DAO', translations: { va: '06 · El patró DAO' } },
                { slug: '13-conexion-bases-datos/07-transacciones', label: '07 · Transacciones', translations: { va: '07 · Transaccions' } },
                { slug: '13-conexion-bases-datos/08-buenas-practicas', label: '08 · Buenas prácticas', translations: { va: '08 · Bones pràctiques' } },
                { slug: '13-conexion-bases-datos/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },
            {
              label: '🌐 14. Servir y Consumir APIs con Web',
              translations: { va: '🌐 14. Servir i Consumir APIs amb Web' },
              items: [
                { slug: '14-apis-web', label: '📌 Índice de la unidad', translations: { va: '📌 Índex de la unitat' } },
                { slug: '14-apis-web/01-protocolo-http', label: '01 · El protocolo HTTP', translations: { va: '01 · El protocol HTTP' } },
                { slug: '14-apis-web/02-servidor-minimo', label: '02 · Servidor web mínimo', translations: { va: '02 · Servidor web mínim' } },
                { slug: '14-apis-web/03-sirviendo-html', label: '03 · Sirviendo HTML', translations: { va: '03 · Servint HTML' } },
                { slug: '14-apis-web/04-get-post', label: '04 · Parámetros GET y POST', translations: { va: '04 · Paràmetres GET i POST' } },
                { slug: '14-apis-web/05-devolviendo-json', label: '05 · Devolviendo JSON', translations: { va: '05 · Tornant JSON' } },
                { slug: '14-apis-web/06-proyecto-rest', label: '06 · Mini proyecto: API REST', translations: { va: '06 · Mini projecte: API REST' } },
                { slug: '14-apis-web/07-httpclient', label: '07 · HttpClient: consumir APIs', translations: { va: '07 · HttpClient: consumir APIs' } },
                { slug: '14-apis-web/08-httpclient-avanzado', label: '08 · HttpClient avanzado', translations: { va: '08 · HttpClient avançat' } },
                { slug: '14-apis-web/09-repaso-interactivo', label: '09 · Repaso interactivo', translations: { va: '09 · Repàs interactiu' } },
              ],
            },

          ],
        },
        {
          label: '📝 Boletines',
          translations: { va: '📝 Butlletins' },
          items:
            ['🚀','🔤','🔀','🅿️','🧩','⚡','🏗️','🔒','🧬','📚','🗺️','📁','🗄️','🌐'].flatMap((emoji, i) => {
              const n = i + 1;
              const nn = String(n).padStart(2,'0');
              return [{
                label: `${emoji} Boletín Unidad ${nn}`,
                translations: { va: `${emoji} Butlletí Unitat ${nn}` },
                items: [
                  { slug: `boletines/boletin-u${nn}-inicial-resuelto`, label: '✅ Inicial resuelto', translations: { va: '✅ Inicial resolt' } },
                  { slug: `boletines/boletin-u${nn}-inicial`, label: '🟢 Inicial por resolver', translations: { va: '🟢 Inicial per resoldre' } },
                  { slug: `boletines/boletin-u${nn}-avanzado-resuelto`, label: '💪 Avanzado resuelto', translations: { va: '💪 Avançat resolt' } },
                  { slug: `boletines/boletin-u${nn}-avanzado`, label: '⭐ Avanzado por resolver', translations: { va: '⭐ Avançat per resoldre' } },
                  { slug: `boletines/boletin-u${nn}-extras`, label: '🔥 Extras', translations: { va: '🔥 Extres' } },
                ],
              }];
            }),
        },
      ],
    }),
  ],
});
